### ISSUE TITLE
Migration Checklist

### ISSUE THREAD

**Issue by qshane** [qshane/quibs.org#33]
- [x] Figure out userpermissions migration
- [x] Migrate gallery and avatar images
- [x] Bring over `new_notifications` schema
- [x] Bring over `fund` schema
- [x] Bring over `fund_btcusd` schema
- [x] Bring over `imageuploads` schema
